# src: ./.github/actions/validate-environment/action.yml
# @(#) : composite GitHub Action to validate runner environment
#
# Copyright (c) 2026- aglabo <https://github.com/aglabo>
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: "Validate Environment"
description: |
  Validate GitHub Actions runner environment.
  REQUIREMENTS: Linux only (ubuntu-latest, ubuntu-22.04, etc.)
  NOT SUPPORTED: Windows, macOS
  Self-hosted runners: allowed by default; set require-github-hosted: "true" to restrict to GitHub-hosted only.
  Note: require-github-hosted relies on RUNNER_ENVIRONMENT set by GitHub Actions (GitHub spec). Self-hosted runners do not set this variable.
  (Note: ARM64 validated on Linux if GitHub provides ARM64 runners)
  Validates: OS/architecture (runner), GitHub permissions, required applications (Git, curl, optional tools)
author: "aglabo"

branding:
  icon: "check-circle"
  color: "green"

inputs:
  architecture:
    description: "Expected runner architecture (canonical format): 'amd64' or 'arm64'. Script normalizes uname -m output (x86_64→amd64, aarch64→arm64). Default: amd64"
    required: false
    default: "amd64"
  actions-type:
    description: "Action type determining required permissions: 'read' (contents: read, default), 'commit' (contents: write), 'pr' (contents: write + pull-requests: write), 'any' (skip permission probe)"
    required: false
    default: "read"
  additional-apps:
    description: |
      Additional applications to validate beyond default (Git, curl).
      Format: Newline-separated list of pipe-delimited (|) definitions.
      Each definition: cmd|app_name|version_extractor|min_version

      version_extractor types (prefix-typed, safe sed-only):
        - field:N = Extract Nth field (space-delimited) from --version output
        - regex:PATTERN = sed -E with capture group \1 (use # as delimiter internally)
        - (empty) = Auto-extract semver (X.Y or X.Y.Z pattern)

      min_version: Minimum required version (empty = skip check, show warning)

      Single app: "gh|gh|regex:version ([0-9.]+)|2.0"
      Multiple apps (use YAML multiline string):
        additional-apps: |
          gh|gh|regex:version ([0-9.]+)|2.0
          node|Node.js|regex:v([0-9.]+)|18.0

      Security: NO eval usage, sed-only extraction, prefix-typed extractors prevent injection
    required: false
    default: ""
  require-github-hosted:
    description: "Require GitHub-hosted runner. 'true': error if runner is not github-hosted. 'false' (default): self-hosted runners allowed"
    required: false
    default: "false"

outputs:
  runner-status:
    description: "Runner validation status (success or error)"
    value: ${{ steps.validate-runner.outputs.status }}
  runner-message:
    description: "Runner validation message"
    value: ${{ steps.validate-runner.outputs.message }}
  permissions-status:
    description: "Permissions validation status (success or error)"
    value: ${{ steps.validate-permissions.outputs.status }}
  permissions-message:
    description: "Permissions validation message (empty if not checked)"
    value: ${{ steps.validate-permissions.outputs.message }}
  apps-status:
    description: "Applications validation status (success or error)"
    value: ${{ steps.validate-apps.outputs.status }}
  apps-message:
    description: "Applications validation message"
    value: ${{ steps.validate-apps.outputs.message }}

runs:
  using: "composite"
  steps:
    # Output mechanism:
    # 1. Scripts write to $GITHUB_OUTPUT (key=value format)
    # 2. Outputs automatically available as steps.<step-id>.outputs.<key>
    # 3. Top-level outputs: section references step outputs for external access
    - name: "Validate Runner and environment variables"
      id: validate-runner
      shell: bash
      env:
        EXPECTED_ARCHITECTURE: ${{ inputs.architecture }}
        REQUIRE_GITHUB_HOSTED: ${{ inputs.require-github-hosted }}
      run: |
        set -euo pipefail
        bash "${GITHUB_ACTION_PATH}/scripts/validate-git-runner.sh"
      # Outputs: status, message (written to $GITHUB_OUTPUT by script)

    - name: "Validate GitHub permissions"
      id: validate-permissions
      shell: bash
      # Note: Uses curl to call the GitHub API.
      # curl is assumed pre-installed on GitHub-hosted Ubuntu runners (standard system tool).
      # curl availability is checked inside validate-permissions.sh before API calls.
      run: |
        set -euo pipefail
        bash "${GITHUB_ACTION_PATH}/scripts/validate-permissions.sh" "${{ inputs.actions-type }}"
      # Outputs: status, message (written to $GITHUB_OUTPUT by script)

    - name: "Validate required applications"
      id: validate-apps
      shell: bash
      run: |
        set -euo pipefail
        bash "${GITHUB_ACTION_PATH}/scripts/validate-apps.sh" <<'APPS_EOF'
        ${{ inputs.additional-apps }}
        APPS_EOF
      # Outputs: status, message
