import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  developerGuide: [{ type: 'autogenerated', dirName: 'developer-guide' }],
  userGuide: [{ type: 'autogenerated', dirName: 'user-guide' }],
};

export default sidebars;
